<a href="https://colab.research.google.com/github/meriemdouider1/10-2022-/blob/main/TEST%202%20SFS%20BED%20CS_LONGIA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sklearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import roc_auc_score, r2_score
import sklearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
import numpy
import sklearn.metrics as metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import LeaveOneOut
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import make_scorer
import matplotlib.pyplot as plt
from sklearn.model_selection import LeaveOneOut
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier
from sklearn import datasets, metrics, model_selection, svm
import numpy as np
from sklearn import svm, datasets
from sklearn.metrics import auc
from sklearn.metrics import plot_roc_curve
from sklearn.model_selection import StratifiedKFold
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier
from sklearn import datasets, metrics, model_selection, svm
from sklearn.metrics import matthews_corrcoef
from sklearn.svm import SVC
from sklearn.metrics import cohen_kappa_score
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.feature_selection import RFE
from sklearn.pipeline import Pipeline
from matplotlib import pyplot

In [ ]:
Cl1 = '/content/cs-longia.xlsx' 
data=pd.read_excel(Cl1, sheet_name=0,header=0,index_col=False, keep_default_na=True)

In [ ]:
data

,Cs_longia,X_long,Y_lat,Bovins,Volaille,Caprins,Ovins,Equides,Coniferes,ZoneAride,...,Vent_Mars,Vent_Avril,Vent_Mai,Vent_Juin,Vent_Juill,Vent_Aout,Vent_Sept,Vent_Oct,Vent_Nov,Vent_Dec
0,1,-15.911420,23.794740,0.000000,0.000000,0.000000,0.000000,0.624435,0,97,...,6.1,6.9,7.2,7.1,7.5,7.2,6.3,5.4,5.5,4.9
1,1,-13.188370,27.132950,0.000214,0.000000,0.063449,0.034352,0.040295,0,100,...,4.8,5.6,5.7,6.4,5.9,5.9,5.7,4.3,3.7,3.8
2,1,-13.188370,27.132950,0.000214,0.000000,0.063449,0.034352,0.040295,0,100,...,4.8,5.6,5.7,6.4,5.9,5.9,5.7,4.3,3.7,3.8
3,0,-13.185620,27.157940,0.000000,0.000000,0.000000,0.000000,0.269410,0,100,...,5.1,5.6,5.5,6.2,6.2,6.2,5.7,4.1,3.7,3.9
4,0,-13.167180,27.157730,0.000000,0.000000,0.000000,0.000000,0.379107,0,100,...,5.0,5.2,5.4,5.7,6.2,5.8,5.6,4.2,3.6,3.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,1,-5.366667,35.766667,8.495770,105.550156,8.691405,15.116930,0.698221,0,0,...,4.6,4.3,4.1,3.9,3.9,4.1,4.0,4.0,4.0,4.2
250,1,-5.816667,35.783333,0.000000,0.000000,0.000000,0.000000,1.725019,0,0,...,4.6,4.1,3.8,3.7,3.7,3.7,3.3,3.6,3.8,4.0
251,1,-5.366667,35.833333,7.411978,111.459663,7.364459,15.054404,0.991284,0,0,...,4.5,4.3,4.0,4.0,3.9,4.0,3.9,4.0,3.9,4.3
252,1,-5.558611,35.841944,5.696193,5.641273,0.602672,4.306276,0.000000,0,0,...,4.6,4.0,3.8,4.1,3.7,3.4,3.6,3.6,3.4,3.6
253,1,-5.483333,35.900000,6.839514,15.082421,0.782080,6.042903,0.595441,0,0,...,4.7,4.4,3.9,3.8,3.9,3.7,4.0,4.0,4.0,4.2

In [ ]:
data["Cs_longia"]

0      1
1      1
2      1
3      0
4      0
      ..
249    1
250    1
251    1
252    1
253    1
Name: Cs_longia, Length: 254, dtype: int64

In [ ]:
X = data.loc[:, data.columns != 'Cs_longia']
y = data.Cs_longia

In [ ]:
X

,X_long,Y_lat,Bovins,Volaille,Caprins,Ovins,Equides,Coniferes,ZoneAride,ZonePel,...,Vent_Mars,Vent_Avril,Vent_Mai,Vent_Juin,Vent_Juill,Vent_Aout,Vent_Sept,Vent_Oct,Vent_Nov,Vent_Dec
0,-15.911420,23.794740,0.000000,0.000000,0.000000,0.000000,0.624435,0,97,3,...,6.1,6.9,7.2,7.1,7.5,7.2,6.3,5.4,5.5,4.9
1,-13.188370,27.132950,0.000214,0.000000,0.063449,0.034352,0.040295,0,100,0,...,4.8,5.6,5.7,6.4,5.9,5.9,5.7,4.3,3.7,3.8
2,-13.188370,27.132950,0.000214,0.000000,0.063449,0.034352,0.040295,0,100,0,...,4.8,5.6,5.7,6.4,5.9,5.9,5.7,4.3,3.7,3.8
3,-13.185620,27.157940,0.000000,0.000000,0.000000,0.000000,0.269410,0,100,0,...,5.1,5.6,5.5,6.2,6.2,6.2,5.7,4.1,3.7,3.9
4,-13.167180,27.157730,0.000000,0.000000,0.000000,0.000000,0.379107,0,100,0,...,5.0,5.2,5.4,5.7,6.2,5.8,5.6,4.2,3.6,3.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,-5.366667,35.766667,8.495770,105.550156,8.691405,15.116930,0.698221,0,0,0,...,4.6,4.3,4.1,3.9,3.9,4.1,4.0,4.0,4.0,4.2
250,-5.816667,35.783333,0.000000,0.000000,0.000000,0.000000,1.725019,0,0,0,...,4.6,4.1,3.8,3.7,3.7,3.7,3.3,3.6,3.8,4.0
251,-5.366667,35.833333,7.411978,111.459663,7.364459,15.054404,0.991284,0,0,0,...,4.5,4.3,4.0,4.0,3.9,4.0,3.9,4.0,3.9,4.3
252,-5.558611,35.841944,5.696193,5.641273,0.602672,4.306276,0.000000,0,0,58,...,4.6,4.0,3.8,4.1,3.7,3.4,3.6,3.6,3.4,3.6
253,-5.483333,35.900000,6.839514,15.082421,0.782080,6.042903,0.595441,0,0,5,...,4.7,4.4,3.9,3.8,3.9,3.7,4.0,4.0,4.0,4.2

In [ ]:
y

0      1
1      1
2      1
3      0
4      0
      ..
249    1
250    1
251    1
252    1
253    1
Name: Cs_longia, Length: 254, dtype: int64

# Test

In [ ]:
# I changed this part
!pip install mlxtend
import joblib
import sys
sys.modules['sklearn.externals.joblib'] = joblib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: mlxtend in /usr/local/lib/python3.7/dist-packages (0.14.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from mlxtend) (57.4.0)
Requirement already satisfied: numpy>=1.10.4 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.21.6)
Requirement already satisfied: scipy>=0.17 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.7.3)
Requirement already satisfied: matplotlib>=1.5.1 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (3.2.2)
Requirement already satisfied: scikit-learn>=0.18 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.0.2)
Requirement already satisfied: pandas>=0.17.1 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.3.5)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.5.1->mlxtend) (0.11.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.5.1->mlxtend) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.5.1->mlxtend) (1.4.4)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.5.1->mlxtend) (3.0.9)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib>=1.5.1->mlxtend) (4.1.1)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.17.1->mlxtend) (2022.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib>=1.5.1->mlxtend) (1.15.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.18->mlxtend) (3.1.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.18->mlxtend) (1.2.0)

In [ ]:
from mlxtend.feature_selection import SequentialFeatureSelector as sfs

In [ ]:
feature_names=X.columns

# Test1  "ACCURACY"

In [11]:
algo = GradientBoostingClassifier(random_state=0)

In [12]:
def specificite(y_true, y_pred):
  specificite= confusion_matrix(y_true, y_pred)[0,0]/(confusion_matrix(y_true,y_pred)[0,0] + confusion_matrix(y_true, y_pred)[0,1])
  return specificite
my_scorer = make_scorer(specificite, greater_is_better=True)
def MCC(y_true, y_pred):
  MCC= matthews_corrcoef(y_true, y_pred) 
  return MCC
my_scorer1 = make_scorer(MCC, greater_is_better=True)
def présicion_positive(y_val, preds):
  cf_matrix = confusion_matrix(y_val, preds)
  pre_pos =  (cf_matrix[1,1])/(cf_matrix[1,1]+cf_matrix[0,1])
  return pre_pos
my_scorer2 = make_scorer(présicion_positive, greater_is_better=True)
def présicion_négative(y_val, preds):
  cf_matrix = confusion_matrix(y_val, preds)
  pre_pos =  (cf_matrix[0,0])/(cf_matrix[0,0]+cf_matrix[1,0])
  return pre_pos
my_scorer3 = make_scorer(présicion_négative, greater_is_better=True)
def VN(y_true, y_pred):
    value = confusion_matrix(y_true, y_pred)[0,0]
    return value
my_scorer4 = make_scorer(VN, greater_is_better=True)
def VP(y_true, y_pred):
    value = confusion_matrix(y_true, y_pred)[1,1]
    return value
my_scorer5 = make_scorer(VP, greater_is_better=True)
def FP(y_true, y_pred):
    value = confusion_matrix(y_true, y_pred)[0,1]
    return value
my_scorer6 = make_scorer(FP, greater_is_better=True)
def FN(y_true, y_pred):
    value = confusion_matrix(y_true, y_pred)[1,0]
    return value
my_scorer7 = make_scorer(FN, greater_is_better=True)

In [13]:
# Build step forward feature selection
sfsT = sfs(algo,
           k_features=20,
           forward= True,
           floating= True,
           verbose=2,
           scoring='accuracy',
           cv= KFold(n_splits=5, random_state=1, shuffle=True))

# Perform SFFS
sfsT = sfsT.fit(np.array(X), y)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.7s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 225 out of 225 | elapsed:  1.2min finished

[2022-10-07 11:38:58] Features: 1/20 -- score: 0.6495686274509804[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.3s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 224 out of 224 | elapsed:  1.2min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.3s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.3s finished

[2022-10-07 11:40:09] Features: 2/20 -- score: 0.7283137254901961[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 223 out of 223 | elapsed:  1.3min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.3s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.7s finished

[2022-10-07 11:41:27] Features: 3/20 -- score: 0.7361568627450981[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 222 out of 222 | elapsed:  1.4min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    1.1s finished

[2022-10-07 11:42:52] Features: 4/20 -- score: 0.767921568627451[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 221 out of 221 | elapsed:  1.5min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    1.5s finished

[2022-10-07 11:44:22] Features: 5/20 -- score: 0.779843137254902[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 220 out of 220 | elapsed:  1.6min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    1.9s finished

[2022-10-07 11:45:58] Features: 6/20 -- score: 0.7797647058823529[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 219 out of 219 | elapsed:  1.6min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:    2.3s finished

[2022-10-07 11:47:35] Features: 7/20 -- score: 0.7836862745098039[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 218 out of 218 | elapsed:  1.6min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:    3.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:    2.4s finished

[2022-10-07 11:49:15] Features: 7/20 -- score: 0.7837647058823529[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 218 out of 218 | elapsed:  1.7min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:    3.1s finished

[2022-10-07 11:50:57] Features: 8/20 -- score: 0.7876862745098039[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 217 out of 217 | elapsed:  1.7min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:    3.7s finished

[2022-10-07 11:52:44] Features: 9/20 -- score: 0.7953725490196077[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 216 out of 216 | elapsed:  1.8min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   9 out of   9 | elapsed:    4.2s finished

[2022-10-07 11:54:38] Features: 10/20 -- score: 0.7992941176470588[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 215 out of 215 | elapsed:  1.8min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    4.8s finished

[2022-10-07 11:56:33] Features: 11/20 -- score: 0.7994509803921568[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 214 out of 214 | elapsed:  1.8min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  11 out of  11 | elapsed:    5.3s finished

[2022-10-07 11:58:29] Features: 12/20 -- score: 0.7916862745098039[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 213 out of 213 | elapsed:  1.9min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:    6.1s finished

[2022-10-07 12:00:27] Features: 13/20 -- score: 0.7916078431372549[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 212 out of 212 | elapsed:  1.9min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  13 out of  13 | elapsed:    6.6s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:    6.1s finished

[2022-10-07 12:02:35] Features: 13/20 -- score: 0.8033725490196078[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 212 out of 212 | elapsed:  1.9min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  13 out of  13 | elapsed:    6.8s finished

[2022-10-07 12:04:37] Features: 14/20 -- score: 0.7994509803921568[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 211 out of 211 | elapsed:  1.9min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  14 out of  14 | elapsed:    7.4s finished

[2022-10-07 12:06:40] Features: 15/20 -- score: 0.7954509803921568[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 210 out of 210 | elapsed:  2.0min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  15 out of  15 | elapsed:    8.1s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  14 out of  14 | elapsed:    7.5s finished

[2022-10-07 12:08:55] Features: 15/20 -- score: 0.7994509803921568[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 210 out of 210 | elapsed:  2.0min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  15 out of  15 | elapsed:    8.2s finished

[2022-10-07 12:11:05] Features: 16/20 -- score: 0.8032941176470587[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 209 out of 209 | elapsed:  2.1min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  16 out of  16 | elapsed:   10.1s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  15 out of  15 | elapsed:    8.4s finished

[2022-10-07 12:13:28] Features: 16/20 -- score: 0.8111372549019608[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 209 out of 209 | elapsed:  2.1min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  16 out of  16 | elapsed:    8.8s finished

[2022-10-07 12:15:42] Features: 17/20 -- score: 0.8032941176470588[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 208 out of 208 | elapsed:  2.1min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  17 out of  17 | elapsed:    9.5s finished

[2022-10-07 12:17:56] Features: 18/20 -- score: 0.8032156862745097[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 207 out of 207 | elapsed:  2.0min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  18 out of  18 | elapsed:   10.2s finished

[2022-10-07 12:20:09] Features: 19/20 -- score: 0.8072156862745098[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 206 out of 206 | elapsed:  2.1min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  19 out of  19 | elapsed:   11.2s finished

[2022-10-07 12:22:24] Features: 20/20 -- score: 0.7992941176470588

In [14]:
R=pd.DataFrame.from_dict(sfsT.get_metric_dict()).T

In [15]:
R

,feature_idx,cv_scores,avg_score,feature_names,ci_bound,std_dev,std_err
1,"(221,)","[0.7058823529411765, 0.6862745098039216, 0.607...",0.649569,"(221,)",0.051707,0.04023,0.020115
2,"(185, 221)","[0.7058823529411765, 0.803921568627451, 0.6666...",0.728314,"(185, 221)",0.058536,0.045543,0.022772
3,"(33, 185, 221)","[0.6862745098039216, 0.7843137254901961, 0.764...",0.736157,"(33, 185, 221)",0.044513,0.034633,0.017316
4,"(33, 180, 185, 221)","[0.7647058823529411, 0.8235294117647058, 0.705...",0.767922,"(33, 180, 185, 221)",0.061544,0.047883,0.023942
5,"(33, 59, 180, 185, 221)","[0.7647058823529411, 0.7843137254901961, 0.764...",0.779843,"(33, 59, 180, 185, 221)",0.057069,0.044402,0.022201
6,"(33, 51, 59, 180, 185, 221)","[0.803921568627451, 0.7843137254901961, 0.7450...",0.779765,"(33, 51, 59, 180, 185, 221)",0.052619,0.040939,0.02047
7,"(33, 52, 59, 70, 180, 185, 221)","[0.7843137254901961, 0.803921568627451, 0.7450...",0.783765,"(33, 52, 59, 70, 180, 185, 221)",0.060585,0.047137,0.023568
8,"(33, 52, 59, 70, 122, 180, 185, 221)","[0.803921568627451, 0.7647058823529411, 0.7843...",0.787686,"(33, 52, 59, 70, 122, 180, 185, 221)",0.057194,0.044499,0.022249
9,"(33, 52, 59, 70, 122, 144, 180, 185, 221)","[0.7843137254901961, 0.8431372549019608, 0.784...",0.795373,"(33, 52, 59, 70, 122, 144, 180, 185, 221)",0.043244,0.033646,0.016823
10,"(16, 33, 52, 59, 70, 122, 144, 180, 185, 221)","[0.7843137254901961, 0.8431372549019608, 0.803...",0.799294,"(16, 33, 52, 59, 70, 122, 144, 180, 185, 221)",0.04276,0.033269,0.016634
11,"(8, 16, 33, 52, 59, 70, 122, 144, 180, 185, 221)","[0.803921568627451, 0.8431372549019608, 0.7647...",0.799451,"(8, 16, 33, 52, 59, 70, 122, 144, 180, 185, 221)",0.063676,0.049542,0.024771
12,"(8, 16, 33, 52, 59, 66, 70, 122, 144, 180, 185...","[0.7647058823529411, 0.8235294117647058, 0.745...",0.791686,"(8, 16, 33, 52, 59, 66, 70, 122, 144, 180, 185...",0.067724,0.052692,0.026346
13,"(8, 16, 33, 39, 59, 65, 66, 70, 122, 144, 180,...","[0.803921568627451, 0.8431372549019608, 0.7450...",0.803373,"(8, 16, 33, 39, 59, 65, 66, 70, 122, 144, 180,...",0.056551,0.043998,0.021999
14,"(8, 16, 33, 39, 52, 59, 65, 66, 70, 122, 144, ...","[0.803921568627451, 0.8431372549019608, 0.7450...",0.799451,"(8, 16, 33, 39, 52, 59, 65, 66, 70, 122, 144, ...",0.061649,0.047965,0.023982
15,"(8, 16, 33, 39, 50, 59, 65, 66, 70, 122, 144, ...","[0.7450980392156863, 0.8235294117647058, 0.784...",0.799451,"(8, 16, 33, 39, 50, 59, 65, 66, 70, 122, 144, ...",0.050302,0.039137,0.019568
16,"(8, 16, 39, 50, 59, 65, 66, 70, 122, 144, 161,...","[0.7254901960784313, 0.8627450980392157, 0.823...",0.811137,"(8, 16, 39, 50, 59, 65, 66, 70, 122, 144, 161,...",0.060388,0.046984,0.023492
17,"(8, 16, 39, 50, 52, 59, 65, 66, 70, 122, 144, ...","[0.7254901960784313, 0.8431372549019608, 0.823...",0.803294,"(8, 16, 39, 50, 52, 59, 65, 66, 70, 122, 144, ...",0.05678,0.044177,0.022088
18,"(8, 9, 16, 39, 50, 52, 59, 65, 66, 70, 122, 14...","[0.7254901960784313, 0.8235294117647058, 0.823...",0.803216,"(8, 9, 16, 39, 50, 52, 59, 65, 66, 70, 122, 14...",0.049981,0.038887,0.019443
19,"(8, 9, 16, 37, 39, 50, 52, 59, 65, 66, 70, 122...","[0.7450980392156863, 0.8235294117647058, 0.803...",0.807216,"(8, 9, 16, 37, 39, 50, 52, 59, 65, 66, 70, 122...",0.042537,0.033095,0.016548
20,"(8, 9, 16, 37, 39, 50, 52, 54, 59, 65, 66, 70,...","[0.7058823529411765, 0.8431372549019608, 0.803...",0.799294,"(8, 9, 16, 37, 39, 50, 52, 54, 59, 65, 66, 70,...",0.062135,0.048344,0.024172

In [19]:
R["feature_idx"][16]

(8, 16, 39, 50, 59, 65, 66, 70, 122, 144, 161, 180, 185, 196, 200, 221)

In [20]:
v16={8, 16, 39, 50, 59, 65, 66, 70, 122, 144, 161, 180, 185, 196, 200, 221}

In [21]:
feat_colsT16 = list(v16)
print(feat_colsT16)
featuresT16=X.columns[feat_colsT16]
X16=X[featuresT16]
X16

[65, 66, 161, 196, 70, 39, 8, 200, 16, 144, 50, 180, 185, 122, 59, 221]

,VarT_bi_NDVI,VarT_tri_NDVI,Prec_Sept,Tmin_Aout,Ph1_NDVI,VarT_cy_TempJ,ZoneAride,Tmin_Dec,VegInond,Bio_Tfr_Moy,VarT_ann_TempN,Tmax_Avril,Tmax_Sept,IPT_Moy,Var_TempN,Vent_Sept
0,1,0,15,18.900000,953,53,97,15.2,0,18.383333,63,22.600000,26.500000,0.375000,3,6.3
1,1,0,1,19.900000,137,87,100,12.8,0,17.450000,72,24.600000,29.200001,-0.281250,9,5.7
2,1,0,1,19.900000,137,87,100,12.8,0,17.450000,72,24.600000,29.200001,-0.281250,9,5.7
3,0,0,0,20.200001,1047,85,100,13.1,0,17.616667,66,24.600000,29.200001,0.898438,8,5.7
4,0,0,1,20.200001,474,77,100,13.2,0,17.750000,72,24.700001,29.400000,-3.468750,9,5.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,3,0,15,21.700001,140,94,0,10.5,0,12.766667,92,18.900000,25.700001,2.828125,19,4.0
250,5,1,19,21.700001,134,95,0,10.5,0,12.816667,91,18.700001,25.700001,1.265625,21,3.3
251,3,1,15,21.799999,173,93,0,10.6,0,12.800000,91,18.900000,25.600000,2.179688,17,3.9
252,5,2,15,20.799999,242,0,0,10.8,11,13.116667,0,19.799999,25.500000,1.406250,0,3.6
253,4,1,15,20.299999,182,92,0,10.6,0,12.883333,91,19.000000,24.799999,5.468750,16,4.0

In [22]:
classifiers = {
"GradientBoosting": GradientBoostingClassifier(random_state=0)
}

cv = KFold(n_splits=5, random_state=1, shuffle=True)
for name, clf in classifiers.items():
    print(name)
    # evaluate model
    scores1 = cross_val_score(clf,  X16, y, scoring='accuracy', cv=cv, n_jobs=-1)
    scores2 = cross_val_score(clf,  X16, y, scoring='recall', cv=cv, n_jobs=-1)
    scores3 = cross_val_score(clf, X16, y, scoring=my_scorer, cv=cv, n_jobs=-1)
    scores4 = cross_val_score(clf, X16, y, scoring=my_scorer1, cv=cv, n_jobs=-1)
    scores5 = cross_val_score(clf, X16, y, scoring=my_scorer2, cv=cv, n_jobs=-1)
    scores6 = cross_val_score(clf, X16, y, scoring=my_scorer3, cv=cv, n_jobs=-1)
    scores7 = cross_val_score(clf,  X16, y, scoring='roc_auc', cv=cv, n_jobs=-1)
    scores8 = cross_val_score(clf,  X16, y, scoring=my_scorer4, cv=cv, n_jobs=-1)
    scores9 = cross_val_score(clf,  X16, y, scoring=my_scorer5, cv=cv, n_jobs=-1)
    scores10 = cross_val_score(clf,  X16, y, scoring=my_scorer6, cv=cv, n_jobs=-1)
    scores11 = cross_val_score(clf,  X16, y, scoring=my_scorer7, cv=cv, n_jobs=-1)
    # report performance
    print('Accuracy:',scores1)
    print('moy_accuracy: %f' % mean(scores1))
    print("-------------------------------------------------")
    print('sensibilité :',scores2)
    print('moy_sensibilité: %f' % mean(scores2))
    print("-------------------------------------------------")
    print('spécificité :',scores3)
    print('moy_spécificité: %f' % mean(scores3))
    print("-------------------------------------------------")
    print('MCC :',scores4)
    print('MCC: %f' % mean(scores4))
    print("-------------------------------------------------")
    print('precision-po:',scores5)
    print('moy_precision-po: %f' % mean(scores5))
    print("-------------------------------------------------")
    print('precision-ne :',scores6)
    print('moy_precision-ne: %f' % mean(scores6))
    print("-------------------------------------------------")
    print('AUC :',scores7)
    print('moy_AUC: %f' % mean(scores7))
    print("-------------------------------------------------")
    print('VN :',scores8)
    print('VP :',scores9)
    print('FP :',scores10)
    print('FN :',scores11)
    print("-------------------------------------------------")
    print("-------------------------------------------------")

GradientBoosting
Accuracy: [0.7254902  0.84313725 0.82352941 0.76470588 0.84      ]
moy_accuracy: 0.799373
-------------------------------------------------
sensibilité : [0.64516129 0.81818182 0.76666667 0.8        0.79166667]
moy_sensibilité: 0.764335
-------------------------------------------------
spécificité : [0.85       0.86206897 0.9047619  0.74193548 0.88461538]
moy_spécificité: 0.848676
-------------------------------------------------
MCC : [0.48584708 0.68025078 0.6610182  0.53009771 0.68065933]
MCC: 0.607575
-------------------------------------------------
precision-po: [0.86956522 0.81818182 0.92       0.66666667 0.86363636]
moy_precision-po: 0.827610
-------------------------------------------------
precision-ne : [0.60714286 0.86206897 0.73076923 0.85185185 0.82142857]
moy_precision-ne: 0.774652
-------------------------------------------------
AUC : [0.71693548 0.88479624 0.78253968 0.85806452 0.86538462]
moy_AUC: 0.821544
-------------------------------------------------
VN : [17 25 19 23 23]
VP : [20 18 23 16 19]
FP : [3 4 2 8 3]
FN : [11  4  7  4  5]
-------------------------------------------------
-------------------------------------------------

In [28]:
R["feature_idx"][17]

(8, 16, 39, 50, 52, 59, 65, 66, 70, 122, 144, 161, 180, 185, 196, 200, 221)

In [33]:
v17={8, 16, 39, 50, 52, 59, 65, 66, 70, 122, 144, 161, 180, 185, 196, 200, 221}

In [34]:
feat_colsT17 = list(v17)
print(feat_colsT17)
featuresT17=X.columns[feat_colsT17]
X17=X[featuresT17]
X17

[65, 66, 161, 196, 70, 39, 8, 200, 16, 144, 50, 52, 180, 185, 122, 59, 221]

,VarT_bi_NDVI,VarT_tri_NDVI,Prec_Sept,Tmin_Aout,Ph1_NDVI,VarT_cy_TempJ,ZoneAride,Tmin_Dec,VegInond,Bio_Tfr_Moy,VarT_ann_TempN,VarT_tri_TempN,Tmax_Avril,Tmax_Sept,IPT_Moy,Var_TempN,Vent_Sept
0,1,0,15,18.900000,953,53,97,15.2,0,18.383333,63,0,22.600000,26.500000,0.375000,3,6.3
1,1,0,1,19.900000,137,87,100,12.8,0,17.450000,72,1,24.600000,29.200001,-0.281250,9,5.7
2,1,0,1,19.900000,137,87,100,12.8,0,17.450000,72,1,24.600000,29.200001,-0.281250,9,5.7
3,0,0,0,20.200001,1047,85,100,13.1,0,17.616667,66,1,24.600000,29.200001,0.898438,8,5.7
4,0,0,1,20.200001,474,77,100,13.2,0,17.750000,72,0,24.700001,29.400000,-3.468750,9,5.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,3,0,15,21.700001,140,94,0,10.5,0,12.766667,92,0,18.900000,25.700001,2.828125,19,4.0
250,5,1,19,21.700001,134,95,0,10.5,0,12.816667,91,0,18.700001,25.700001,1.265625,21,3.3
251,3,1,15,21.799999,173,93,0,10.6,0,12.800000,91,0,18.900000,25.600000,2.179688,17,3.9
252,5,2,15,20.799999,242,0,0,10.8,11,13.116667,0,0,19.799999,25.500000,1.406250,0,3.6
253,4,1,15,20.299999,182,92,0,10.6,0,12.883333,91,0,19.000000,24.799999,5.468750,16,4.0

In [35]:
classifiers = {
"GradientBoosting": GradientBoostingClassifier(random_state=0)
}

cv = KFold(n_splits=5, random_state=1, shuffle=True)
for name, clf in classifiers.items():
    print(name)
    # evaluate model
    scores1 = cross_val_score(clf,  X17, y, scoring='accuracy', cv=cv, n_jobs=-1)
    scores2 = cross_val_score(clf,  X17, y, scoring='recall', cv=cv, n_jobs=-1)
    scores3 = cross_val_score(clf, X17, y, scoring=my_scorer, cv=cv, n_jobs=-1)
    scores4 = cross_val_score(clf, X17, y, scoring=my_scorer1, cv=cv, n_jobs=-1)
    scores5 = cross_val_score(clf, X17, y, scoring=my_scorer2, cv=cv, n_jobs=-1)
    scores6 = cross_val_score(clf, X17, y, scoring=my_scorer3, cv=cv, n_jobs=-1)
    scores7 = cross_val_score(clf,  X17, y, scoring='roc_auc', cv=cv, n_jobs=-1)
    scores8 = cross_val_score(clf,  X17, y, scoring=my_scorer4, cv=cv, n_jobs=-1)
    scores9 = cross_val_score(clf,  X17, y, scoring=my_scorer5, cv=cv, n_jobs=-1)
    scores10 = cross_val_score(clf,  X17, y, scoring=my_scorer6, cv=cv, n_jobs=-1)
    scores11 = cross_val_score(clf,  X17, y, scoring=my_scorer7, cv=cv, n_jobs=-1)
    # report performance
    print('Accuracy:',scores1)
    print('moy_accuracy: %f' % mean(scores1))
    print("-------------------------------------------------")
    print('sensibilité :',scores2)
    print('moy_sensibilité: %f' % mean(scores2))
    print("-------------------------------------------------")
    print('spécificité :',scores3)
    print('moy_spécificité: %f' % mean(scores3))
    print("-------------------------------------------------")
    print('MCC :',scores4)
    print('MCC: %f' % mean(scores4))
    print("-------------------------------------------------")
    print('precision-po:',scores5)
    print('moy_precision-po: %f' % mean(scores5))
    print("-------------------------------------------------")
    print('precision-ne :',scores6)
    print('moy_precision-ne: %f' % mean(scores6))
    print("-------------------------------------------------")
    print('AUC :',scores7)
    print('moy_AUC: %f' % mean(scores7))
    print("-------------------------------------------------")
    print('VN :',scores8)
    print('VP :',scores9)
    print('FP :',scores10)
    print('FN :',scores11)
    print("-------------------------------------------------")
    print("-------------------------------------------------")

GradientBoosting
Accuracy: [0.7254902  0.84313725 0.82352941 0.78431373 0.84      ]
moy_accuracy: 0.803294
-------------------------------------------------
sensibilité : [0.64516129 0.81818182 0.76666667 0.85       0.79166667]
moy_sensibilité: 0.774335
-------------------------------------------------
spécificité : [0.85       0.86206897 0.9047619  0.74193548 0.88461538]
moy_spécificité: 0.848676
-------------------------------------------------
MCC : [0.48584708 0.68025078 0.6610182  0.57811407 0.68065933]
MCC: 0.617178
-------------------------------------------------
precision-po: [0.86956522 0.81818182 0.92       0.68       0.86363636]
moy_precision-po: 0.830277
-------------------------------------------------
precision-ne : [0.60714286 0.86206897 0.73076923 0.88461538 0.82142857]
moy_precision-ne: 0.781205
-------------------------------------------------
AUC : [0.72822581 0.88322884 0.78888889 0.85       0.86378205]
moy_AUC: 0.822825
-------------------------------------------------
VN : [17 25 19 23 23]
VP : [20 18 23 17 19]
FP : [3 4 2 8 3]
FN : [11  4  7  3  5]
-------------------------------------------------
-------------------------------------------------

# test mcc

In [37]:
# Build step forward feature selection
sfsTM = sfs(algo,
           k_features=20,
           forward= True,
           floating= True,
           verbose=2,
           scoring=my_scorer1,
           cv= KFold(n_splits=5, random_state=1, shuffle=True))

# Perform SFFS
sfsTM = sfsTM.fit(np.array(X), y)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.3s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 225 out of 225 | elapsed:  1.1min finished

[2022-10-07 12:36:16] Features: 1/20 -- score: 0.3354026493568424[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.8s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 224 out of 224 | elapsed:  1.2min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.3s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.3s finished

[2022-10-07 12:37:30] Features: 2/20 -- score: 0.4670211643784258[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 223 out of 223 | elapsed:  1.3min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.7s finished

[2022-10-07 12:38:48] Features: 3/20 -- score: 0.48500052287568085[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 222 out of 222 | elapsed:  1.4min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    1.1s finished

[2022-10-07 12:40:13] Features: 4/20 -- score: 0.5366666500779139[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 221 out of 221 | elapsed:  1.5min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    1.5s finished

[2022-10-07 12:41:44] Features: 5/20 -- score: 0.5603141696146213[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 220 out of 220 | elapsed:  1.5min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    2.0s finished

[2022-10-07 12:43:18] Features: 6/20 -- score: 0.5685816573023968[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 219 out of 219 | elapsed:  1.6min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:    2.7s finished

[2022-10-07 12:44:55] Features: 7/20 -- score: 0.5852480316761768[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 218 out of 218 | elapsed:  1.7min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:    2.9s finished

[2022-10-07 12:46:38] Features: 8/20 -- score: 0.5898386514383349[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 217 out of 217 | elapsed:  1.6min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:    3.4s finished

[2022-10-07 12:48:21] Features: 9/20 -- score: 0.5834365435890285[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 216 out of 216 | elapsed:  1.7min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   9 out of   9 | elapsed:    3.9s finished

[2022-10-07 12:50:05] Features: 10/20 -- score: 0.5834365435890285[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 215 out of 215 | elapsed:  1.7min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    4.6s finished

[2022-10-07 12:51:51] Features: 11/20 -- score: 0.577540632398156[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 214 out of 214 | elapsed:  1.8min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  11 out of  11 | elapsed:    5.2s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    4.7s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   9 out of   9 | elapsed:    4.2s finished

[2022-10-07 12:53:51] Features: 10/20 -- score: 0.6090065943483178[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 215 out of 215 | elapsed:  1.8min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    4.8s finished

[2022-10-07 12:55:45] Features: 11/20 -- score: 0.5940608478112501[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 214 out of 214 | elapsed:  1.8min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  11 out of  11 | elapsed:    5.5s finished

[2022-10-07 12:57:39] Features: 12/20 -- score: 0.596322341124912[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 213 out of 213 | elapsed:  1.9min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:    6.0s finished

[2022-10-07 12:59:37] Features: 13/20 -- score: 0.5850600513225188[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 212 out of 212 | elapsed:  1.9min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  13 out of  13 | elapsed:    6.7s finished

[2022-10-07 13:01:40] Features: 14/20 -- score: 0.6087158567136964[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 211 out of 211 | elapsed:  2.0min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  14 out of  14 | elapsed:    7.3s finished

[2022-10-07 13:03:45] Features: 15/20 -- score: 0.6087158567136964[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 210 out of 210 | elapsed:  1.9min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  15 out of  15 | elapsed:    8.2s finished

[2022-10-07 13:05:50] Features: 16/20 -- score: 0.5918343352203634[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 209 out of 209 | elapsed:  2.0min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  16 out of  16 | elapsed:    8.8s finished

[2022-10-07 13:08:01] Features: 17/20 -- score: 0.5835133340612384[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 208 out of 208 | elapsed:  2.1min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  17 out of  17 | elapsed:    9.8s finished

[2022-10-07 13:10:14] Features: 18/20 -- score: 0.5858581128364725[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 207 out of 207 | elapsed:  2.2min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  18 out of  18 | elapsed:   10.5s finished

[2022-10-07 13:12:34] Features: 19/20 -- score: 0.5886424664174769[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 206 out of 206 | elapsed:  2.1min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  19 out of  19 | elapsed:   11.5s finished

[2022-10-07 13:14:54] Features: 20/20 -- score: 0.5792784051232834

In [38]:
H=pd.DataFrame.from_dict(sfsTM.get_metric_dict()).T

In [39]:
H

,feature_idx,cv_scores,avg_score,feature_names,ci_bound,std_dev,std_err
1,"(221,)","[0.5091777436068423, 0.40694816252947663, 0.23...",0.335403,"(221,)",0.137413,0.106912,0.053456
2,"(185, 221)","[0.4174393166995065, 0.6164863840991135, 0.376...",0.467021,"(185, 221)",0.105839,0.082346,0.041173
3,"(33, 185, 221)","[0.452790349024556, 0.5714533736737374, 0.5227...",0.485001,"(33, 185, 221)",0.068489,0.053287,0.026643
4,"(33, 180, 185, 221)","[0.516746063443483, 0.639029552665605, 0.42192...",0.536667,"(33, 180, 185, 221)",0.114299,0.088929,0.044464
5,"(17, 33, 180, 185, 221)","[0.4662718405398261, 0.5583707346334679, 0.549...",0.560314,"(17, 33, 180, 185, 221)",0.13868,0.107898,0.053949
6,"(17, 20, 33, 180, 185, 221)","[0.4806451612903226, 0.6802507836990596, 0.549...",0.568582,"(17, 20, 33, 180, 185, 221)",0.134617,0.104737,0.052368
7,"(17, 20, 33, 180, 185, 212, 221)","[0.5358562044211472, 0.6802507836990596, 0.581...",0.585248,"(17, 20, 33, 180, 185, 212, 221)",0.102195,0.079511,0.039755
8,"(17, 20, 33, 52, 180, 185, 212, 221)","[0.5358562044211472, 0.6802507836990596, 0.534...",0.589839,"(17, 20, 33, 52, 180, 185, 212, 221)",0.128198,0.099742,0.049871
9,"(8, 17, 20, 33, 52, 180, 185, 212, 221)","[0.5088162823815585, 0.6789248279703607, 0.534...",0.583437,"(8, 17, 20, 33, 52, 180, 185, 212, 221)",0.11112,0.086455,0.043227
10,"(8, 17, 20, 33, 36, 125, 180, 185, 212, 221)","[0.6472685856114562, 0.6822534312604148, 0.567...",0.609007,"(8, 17, 20, 33, 36, 125, 180, 185, 212, 221)",0.086351,0.067184,0.033592
11,"(8, 16, 17, 20, 33, 36, 125, 180, 185, 212, 221)","[0.6472685856114562, 0.639029552665605, 0.5678...",0.594061,"(8, 16, 17, 20, 33, 36, 125, 180, 185, 212, 221)",0.090864,0.070695,0.035348
12,"(8, 16, 17, 20, 33, 36, 125, 180, 185, 211, 21...","[0.6768211858110855, 0.639029552665605, 0.5180...",0.596322,"(8, 16, 17, 20, 33, 36, 125, 180, 185, 211, 21...",0.094461,0.073494,0.036747
13,"(8, 16, 17, 20, 33, 36, 125, 160, 180, 185, 21...","[0.5158986661077505, 0.6822534312604148, 0.629...",0.58506,"(8, 16, 17, 20, 33, 36, 125, 160, 180, 185, 21...",0.121344,0.094409,0.047205
14,"(8, 16, 17, 20, 33, 36, 125, 157, 160, 180, 18...","[0.6768211858110855, 0.6056255902580893, 0.549...",0.608716,"(8, 16, 17, 20, 33, 36, 125, 157, 160, 180, 18...",0.102123,0.079455,0.039728
15,"(8, 16, 17, 20, 33, 36, 52, 125, 157, 160, 180...","[0.6768211858110855, 0.6056255902580893, 0.549...",0.608716,"(8, 16, 17, 20, 33, 36, 52, 125, 157, 160, 180...",0.102123,0.079455,0.039728
16,"(8, 16, 17, 20, 33, 36, 52, 112, 125, 157, 160...","[0.6472685856114562, 0.516746063443483, 0.5678...",0.591834,"(8, 16, 17, 20, 33, 36, 52, 112, 125, 157, 160...",0.089428,0.069578,0.034789
17,"(8, 10, 16, 17, 20, 33, 36, 52, 112, 125, 157,...","[0.596359925959418, 0.5583707346334679, 0.5678...",0.583513,"(8, 10, 16, 17, 20, 33, 36, 52, 112, 125, 157,...",0.083937,0.065306,0.032653
18,"(8, 10, 16, 17, 20, 33, 36, 52, 112, 125, 137,...","[0.5466092184706746, 0.5978354457069218, 0.619...",0.585858,"(8, 10, 16, 17, 20, 33, 36, 52, 112, 125, 137,...",0.062389,0.048541,0.02427
19,"(8, 10, 16, 17, 20, 33, 36, 52, 112, 125, 137,...","[0.6584514504920518, 0.5978354457069218, 0.590...",0.588642,"(8, 10, 16, 17, 20, 33, 36, 52, 112, 125, 137,...",0.074553,0.058005,0.029002
20,"(8, 10, 16, 17, 20, 33, 36, 39, 52, 112, 125, ...","[0.6584514504920518, 0.5583707346334679, 0.619...",0.579278,"(8, 10, 16, 17, 20, 33, 36, 39, 52, 112, 125, ...",0.06577,0.051171,0.025586

In [59]:
H["feature_idx"][14]

(8, 16, 17, 20, 33, 36, 125, 157, 160, 180, 185, 211, 212, 221)

In [64]:
v14={8, 16, 17, 20, 33, 36, 125, 157, 160, 180, 185, 211, 212, 221}

In [65]:
feat_colsT14 = list(v14)
print(feat_colsT14)
featuresT14=X.columns[feat_colsT14]
X14=X[featuresT14]
X14

[160, 33, 36, 8, 16, 17, 211, 20, 180, 157, 212, 221, 185, 125]

,Prec_Aout,Amp1_TempJ,VarT_ann_TempJ,ZoneAride,VegInond,ZoneUrbaine,Vap_Nov,Amp2_IRM,Tmax_Avril,Prec_Mai,Vap_Dec,Vent_Sept,Tmax_Sept,IR_Med
0,3,96,30,97,0,0,1.71,110,22.600000,1,1.47,6.3,26.500000,1.6250
1,0,312,74,100,0,0,1.60,10,24.600000,0,1.39,5.7,29.200001,1.3750
2,0,312,74,100,0,0,1.60,10,24.600000,0,1.39,5.7,29.200001,1.3750
3,0,306,74,100,0,0,1.61,40,24.600000,0,1.40,5.7,29.200001,9.4375
4,0,295,66,100,0,0,1.63,70,24.700001,0,1.41,5.6,29.400000,6.1250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,3,543,92,0,0,0,1.35,70,18.900000,33,1.19,4.0,25.700001,25.1875
250,2,478,94,0,0,100,1.37,0,18.700001,39,1.21,3.3,25.700001,5.9375
251,4,452,91,0,0,0,1.35,140,18.900000,33,1.19,3.9,25.600000,15.5000
252,2,0,0,0,11,0,1.39,100,19.799999,34,1.22,3.6,25.500000,11.8750
253,3,366,91,0,0,0,1.37,70,19.000000,33,1.21,4.0,24.799999,25.0625

In [66]:
X14

,Prec_Aout,Amp1_TempJ,VarT_ann_TempJ,ZoneAride,VegInond,ZoneUrbaine,Vap_Nov,Amp2_IRM,Tmax_Avril,Prec_Mai,Vap_Dec,Vent_Sept,Tmax_Sept,IR_Med
0,3,96,30,97,0,0,1.71,110,22.600000,1,1.47,6.3,26.500000,1.6250
1,0,312,74,100,0,0,1.60,10,24.600000,0,1.39,5.7,29.200001,1.3750
2,0,312,74,100,0,0,1.60,10,24.600000,0,1.39,5.7,29.200001,1.3750
3,0,306,74,100,0,0,1.61,40,24.600000,0,1.40,5.7,29.200001,9.4375
4,0,295,66,100,0,0,1.63,70,24.700001,0,1.41,5.6,29.400000,6.1250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,3,543,92,0,0,0,1.35,70,18.900000,33,1.19,4.0,25.700001,25.1875
250,2,478,94,0,0,100,1.37,0,18.700001,39,1.21,3.3,25.700001,5.9375
251,4,452,91,0,0,0,1.35,140,18.900000,33,1.19,3.9,25.600000,15.5000
252,2,0,0,0,11,0,1.39,100,19.799999,34,1.22,3.6,25.500000,11.8750
253,3,366,91,0,0,0,1.37,70,19.000000,33,1.21,4.0,24.799999,25.0625

In [67]:
classifiers = {
"GradientBoosting": GradientBoostingClassifier(random_state=0)
}

cv = KFold(n_splits=5, random_state=1, shuffle=True)
for name, clf in classifiers.items():
    print(name)
    # evaluate model
    scores1 = cross_val_score(clf,  X14, y, scoring='accuracy', cv=cv, n_jobs=-1)
    scores2 = cross_val_score(clf,  X14, y, scoring='recall', cv=cv, n_jobs=-1)
    scores3 = cross_val_score(clf, X14, y, scoring=my_scorer, cv=cv, n_jobs=-1)
    scores4 = cross_val_score(clf, X14, y, scoring=my_scorer1, cv=cv, n_jobs=-1)
    scores5 = cross_val_score(clf, X14, y, scoring=my_scorer2, cv=cv, n_jobs=-1)
    scores6 = cross_val_score(clf, X14, y, scoring=my_scorer3, cv=cv, n_jobs=-1)
    scores7 = cross_val_score(clf,  X14, y, scoring='roc_auc', cv=cv, n_jobs=-1)
    scores8 = cross_val_score(clf,  X14, y, scoring=my_scorer4, cv=cv, n_jobs=-1)
    scores9 = cross_val_score(clf,  X14, y, scoring=my_scorer5, cv=cv, n_jobs=-1)
    scores10 = cross_val_score(clf,  X14, y, scoring=my_scorer6, cv=cv, n_jobs=-1)
    scores11 = cross_val_score(clf,  X14, y, scoring=my_scorer7, cv=cv, n_jobs=-1)
    # report performance
    print('Accuracy:',scores1)
    print('moy_accuracy: %f' % mean(scores1))
    print("-------------------------------------------------")
    print('sensibilité :',scores2)
    print('moy_sensibilité: %f' % mean(scores2))
    print("-------------------------------------------------")
    print('spécificité :',scores3)
    print('moy_spécificité: %f' % mean(scores3))
    print("-------------------------------------------------")
    print('MCC :',scores4)
    print('MCC: %f' % mean(scores4))
    print("-------------------------------------------------")
    print('precision-po:',scores5)
    print('moy_precision-po: %f' % mean(scores5))
    print("-------------------------------------------------")
    print('precision-ne :',scores6)
    print('moy_precision-ne: %f' % mean(scores6))
    print("-------------------------------------------------")
    print('AUC :',scores7)
    print('moy_AUC: %f' % mean(scores7))
    print("-------------------------------------------------")
    print('VN :',scores8)
    print('VP :',scores9)
    print('FP :',scores10)
    print('FN :',scores11)
    print("-------------------------------------------------")
    print("-------------------------------------------------")

GradientBoosting
Accuracy: [0.82352941 0.80392157 0.76470588 0.74509804 0.84      ]
moy_accuracy: 0.795451
-------------------------------------------------
sensibilité : [0.74193548 0.63636364 0.7        0.8        0.66666667]
moy_sensibilité: 0.708993
-------------------------------------------------
spécificité : [0.95       0.93103448 0.85714286 0.70967742 1.        ]
moy_spécificité: 0.889571
-------------------------------------------------
MCC : [0.67682119 0.60562559 0.54935027 0.49777669 0.71400555]
MCC: 0.608716
-------------------------------------------------
precision-po: [0.95833333 0.875      0.875      0.64       1.        ]
moy_precision-po: 0.869667
-------------------------------------------------
precision-ne : [0.7037037  0.77142857 0.66666667 0.84615385 0.76470588]
moy_precision-ne: 0.750532
-------------------------------------------------
AUC : [0.81370968 0.80172414 0.79206349 0.75       0.79407051]
moy_AUC: 0.790314
-------------------------------------------------
VN : [19 27 18 22 26]
VP : [23 14 21 16 16]
FP : [1 2 3 9 0]
FN : [8 8 9 4 8]
-------------------------------------------------
-------------------------------------------------

In [68]:
X14.columns

Index(['Prec_Aout', 'Amp1_TempJ', 'VarT_ann_TempJ', 'ZoneAride', 'VegInond',
       'ZoneUrbaine', 'Vap_Nov', 'Amp2_IRM', 'Tmax_Avril', 'Prec_Mai',
       'Vap_Dec', 'Vent_Sept', 'Tmax_Sept', 'IR_Med'],
      dtype='object')