<a href="https://colab.research.google.com/github/meriemdouider1/10-2022--12-2022/blob/main/Cs_longia/%20Nouvelle_modele_10_janv_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# -----

In [ ]:
import sklearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import roc_auc_score, r2_score
import sklearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
import numpy
import sklearn.metrics as metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import LeaveOneOut
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import make_scorer
import matplotlib.pyplot as plt
from sklearn.model_selection import LeaveOneOut
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier
from sklearn import datasets, metrics, model_selection, svm
import numpy as np
from sklearn import svm, datasets
from sklearn.metrics import auc
from sklearn.metrics import plot_roc_curve
from sklearn.model_selection import StratifiedKFold
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier
from sklearn import datasets, metrics, model_selection, svm
from sklearn.metrics import matthews_corrcoef
from sklearn.svm import SVC
from sklearn.metrics import cohen_kappa_score
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.feature_selection import RFE
from sklearn.pipeline import Pipeline
from matplotlib import pyplot

In [ ]:
Cl1 = '/content/cs-longia.xlsx' 
data=pd.read_excel(Cl1, sheet_name=0,header=0,index_col=False, keep_default_na=True)

In [ ]:
data

,Cs_longia,X_long,Y_lat,Bovins,Volaille,Caprins,Ovins,Equides,Coniferes,ZoneAride,...,Vent_Mars,Vent_Avril,Vent_Mai,Vent_Juin,Vent_Juill,Vent_Aout,Vent_Sept,Vent_Oct,Vent_Nov,Vent_Dec
0,1,-15.911420,23.794740,0.000000,0.000000,0.000000,0.000000,0.624435,0,97,...,6.1,6.9,7.2,7.1,7.5,7.2,6.3,5.4,5.5,4.9
1,1,-13.188370,27.132950,0.000214,0.000000,0.063449,0.034352,0.040295,0,100,...,4.8,5.6,5.7,6.4,5.9,5.9,5.7,4.3,3.7,3.8
2,1,-13.188370,27.132950,0.000214,0.000000,0.063449,0.034352,0.040295,0,100,...,4.8,5.6,5.7,6.4,5.9,5.9,5.7,4.3,3.7,3.8
3,0,-13.185620,27.157940,0.000000,0.000000,0.000000,0.000000,0.269410,0,100,...,5.1,5.6,5.5,6.2,6.2,6.2,5.7,4.1,3.7,3.9
4,0,-13.167180,27.157730,0.000000,0.000000,0.000000,0.000000,0.379107,0,100,...,5.0,5.2,5.4,5.7,6.2,5.8,5.6,4.2,3.6,3.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,1,-5.366667,35.766667,8.495770,105.550156,8.691405,15.116930,0.698221,0,0,...,4.6,4.3,4.1,3.9,3.9,4.1,4.0,4.0,4.0,4.2
250,1,-5.816667,35.783333,0.000000,0.000000,0.000000,0.000000,1.725019,0,0,...,4.6,4.1,3.8,3.7,3.7,3.7,3.3,3.6,3.8,4.0
251,1,-5.366667,35.833333,7.411978,111.459663,7.364459,15.054404,0.991284,0,0,...,4.5,4.3,4.0,4.0,3.9,4.0,3.9,4.0,3.9,4.3
252,1,-5.558611,35.841944,5.696193,5.641273,0.602672,4.306276,0.000000,0,0,...,4.6,4.0,3.8,4.1,3.7,3.4,3.6,3.6,3.4,3.6
253,1,-5.483333,35.900000,6.839514,15.082421,0.782080,6.042903,0.595441,0,0,...,4.7,4.4,3.9,3.8,3.9,3.7,4.0,4.0,4.0,4.2

In [ ]:
data["Cs_longia"]

0      1
1      1
2      1
3      0
4      0
      ..
249    1
250    1
251    1
252    1
253    1
Name: Cs_longia, Length: 254, dtype: int64

In [ ]:
X = data.loc[:, data.columns != 'Cs_longia']
y = data.Cs_longia

In [ ]:
X

,X_long,Y_lat,Bovins,Volaille,Caprins,Ovins,Equides,Coniferes,ZoneAride,ZonePel,...,Vent_Mars,Vent_Avril,Vent_Mai,Vent_Juin,Vent_Juill,Vent_Aout,Vent_Sept,Vent_Oct,Vent_Nov,Vent_Dec
0,-15.911420,23.794740,0.000000,0.000000,0.000000,0.000000,0.624435,0,97,3,...,6.1,6.9,7.2,7.1,7.5,7.2,6.3,5.4,5.5,4.9
1,-13.188370,27.132950,0.000214,0.000000,0.063449,0.034352,0.040295,0,100,0,...,4.8,5.6,5.7,6.4,5.9,5.9,5.7,4.3,3.7,3.8
2,-13.188370,27.132950,0.000214,0.000000,0.063449,0.034352,0.040295,0,100,0,...,4.8,5.6,5.7,6.4,5.9,5.9,5.7,4.3,3.7,3.8
3,-13.185620,27.157940,0.000000,0.000000,0.000000,0.000000,0.269410,0,100,0,...,5.1,5.6,5.5,6.2,6.2,6.2,5.7,4.1,3.7,3.9
4,-13.167180,27.157730,0.000000,0.000000,0.000000,0.000000,0.379107,0,100,0,...,5.0,5.2,5.4,5.7,6.2,5.8,5.6,4.2,3.6,3.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,-5.366667,35.766667,8.495770,105.550156,8.691405,15.116930,0.698221,0,0,0,...,4.6,4.3,4.1,3.9,3.9,4.1,4.0,4.0,4.0,4.2
250,-5.816667,35.783333,0.000000,0.000000,0.000000,0.000000,1.725019,0,0,0,...,4.6,4.1,3.8,3.7,3.7,3.7,3.3,3.6,3.8,4.0
251,-5.366667,35.833333,7.411978,111.459663,7.364459,15.054404,0.991284,0,0,0,...,4.5,4.3,4.0,4.0,3.9,4.0,3.9,4.0,3.9,4.3
252,-5.558611,35.841944,5.696193,5.641273,0.602672,4.306276,0.000000,0,0,58,...,4.6,4.0,3.8,4.1,3.7,3.4,3.6,3.6,3.4,3.6
253,-5.483333,35.900000,6.839514,15.082421,0.782080,6.042903,0.595441,0,0,5,...,4.7,4.4,3.9,3.8,3.9,3.7,4.0,4.0,4.0,4.2

# ------

In [ ]:
def specificite(y_true, y_pred):
  specificite= confusion_matrix(y_true, y_pred)[0,0]/(confusion_matrix(y_true,y_pred)[0,0] + confusion_matrix(y_true, y_pred)[0,1])
  return specificite
my_scorer = make_scorer(specificite, greater_is_better=True)
def MCC(y_true, y_pred):
  MCC= matthews_corrcoef(y_true, y_pred) 
  return MCC
my_scorer1 = make_scorer(MCC, greater_is_better=True)
def présicion_positive(y_val, preds):
  cf_matrix = confusion_matrix(y_val, preds)
  pre_pos =  (cf_matrix[1,1])/(cf_matrix[1,1]+cf_matrix[0,1])
  return pre_pos
my_scorer2 = make_scorer(présicion_positive, greater_is_better=True)
def présicion_négative(y_val, preds):
  cf_matrix = confusion_matrix(y_val, preds)
  pre_pos =  (cf_matrix[0,0])/(cf_matrix[0,0]+cf_matrix[1,0])
  return pre_pos
my_scorer3 = make_scorer(présicion_négative, greater_is_better=True)
def VN(y_true, y_pred):
    value = confusion_matrix(y_true, y_pred)[0,0]
    return value
my_scorer4 = make_scorer(VN, greater_is_better=True)
def VP(y_true, y_pred):
    value = confusion_matrix(y_true, y_pred)[1,1]
    return value
my_scorer5 = make_scorer(VP, greater_is_better=True)
def FP(y_true, y_pred):
    value = confusion_matrix(y_true, y_pred)[0,1]
    return value
my_scorer6 = make_scorer(FP, greater_is_better=True)
def FN(y_true, y_pred):
    value = confusion_matrix(y_true, y_pred)[1,0]
    return value
my_scorer7 = make_scorer(FN, greater_is_better=True)

In [ ]:
lst1= ['X_long', 'VegInond', 'Min_IRM','Var_IRM' ,'VarT_ann_TempJ','VarT_tri_TempJ','VarT_tri_NDVI','IR_sd','RV_Med','RV_Min','Bio_Tint','Prec_Avril','Prec_Juin','Prec_Juill','Prec_Aout','Prec_Dec','Tmax_Janv','Tmax_Avril','Tmax_Sept','Tmin_Juin','Vap_Mai','Vent_Juin']

In [ ]:
X1=X[lst1]

In [ ]:
X1

,X_long,VegInond,Min_IRM,Var_IRM,VarT_ann_TempJ,VarT_tri_TempJ,VarT_tri_NDVI,IR_sd,RV_Med,RV_Min,...,Prec_Juin,Prec_Juill,Prec_Aout,Prec_Dec,Tmax_Janv,Tmax_Avril,Tmax_Sept,Tmin_Juin,Vap_Mai,Vent_Juin
0,-15.911420,0,2690,0,30,0,0,0.899761,0.000025,0.000009,...,0,1,3,15,21.5,22.600000,26.500000,17.299999,1.72,7.1
1,-13.188370,0,3350,0,74,1,0,0.397748,0.000006,0.000002,...,1,0,0,8,21.9,24.600000,29.200001,17.299999,1.62,6.4
2,-13.188370,0,3350,0,74,1,0,0.397748,0.000006,0.000002,...,1,0,0,8,21.9,24.600000,29.200001,17.299999,1.62,6.4
3,-13.185620,0,2930,0,74,0,0,1.639937,0.000175,0.000054,...,1,0,0,8,21.9,24.600000,29.200001,17.600000,1.64,6.2
4,-13.167180,0,2350,10,66,1,0,3.913587,0.000403,0.000150,...,1,0,0,8,22.0,24.700001,29.400000,17.700001,1.65,5.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,-5.366667,0,880,0,92,0,0,2.176535,0.000837,0.000547,...,7,1,3,132,15.2,18.900000,25.700001,18.500000,1.47,3.9
250,-5.816667,0,1400,0,94,0,1,1.735360,0.000184,0.000052,...,13,1,2,142,14.5,18.700001,25.700001,19.400000,1.48,3.7
251,-5.366667,0,1080,0,91,0,1,3.989664,0.001003,0.000710,...,7,1,4,133,15.3,18.900000,25.600000,18.400000,1.47,4.0
252,-5.558611,11,620,0,0,0,2,12.156531,0.001606,0.000286,...,7,1,2,140,16.6,19.799999,25.500000,16.700001,1.52,4.1
253,-5.483333,0,990,0,91,0,1,19.463408,0.007986,0.002183,...,7,1,3,141,16.0,19.000000,24.799999,16.600000,1.49,3.8

In [ ]:
classifiers = {
"Gradient_boosting": GradientBoostingClassifier(random_state=0)
}

cv = KFold(n_splits=5, random_state=1, shuffle=True)
for name, clf in classifiers.items():
    print(name)
    # evaluate model
    scores1 = cross_val_score(clf,  X1, y, scoring='accuracy', cv=cv, n_jobs=-1)
    scores2 = cross_val_score(clf,  X1, y, scoring='recall', cv=cv, n_jobs=-1)
    scores3 = cross_val_score(clf, X1, y, scoring=my_scorer, cv=cv, n_jobs=-1)
    scores4 = cross_val_score(clf, X1, y, scoring=my_scorer1, cv=cv, n_jobs=-1)
    scores5 = cross_val_score(clf, X1, y, scoring=my_scorer2, cv=cv, n_jobs=-1)
    scores6 = cross_val_score(clf, X1, y, scoring=my_scorer3, cv=cv, n_jobs=-1)
    scores7 = cross_val_score(clf,  X1, y, scoring='roc_auc', cv=cv, n_jobs=-1)
    scores8 = cross_val_score(clf,  X1, y, scoring=my_scorer4, cv=cv, n_jobs=-1)
    scores9 = cross_val_score(clf,  X1, y, scoring=my_scorer5, cv=cv, n_jobs=-1)
    scores10 = cross_val_score(clf,  X1, y, scoring=my_scorer6, cv=cv, n_jobs=-1)
    scores11 = cross_val_score(clf,  X1, y, scoring=my_scorer7, cv=cv, n_jobs=-1)
    # report performance
    print('Accuracy:',scores1)
    print('moy_accuracy: %f' % mean(scores1))
    print("-------------------------------------------------")
    print('sensibilité :',scores2)
    print('moy_sensibilité: %f' % mean(scores2))
    print("-------------------------------------------------")
    print('spécificité :',scores3)
    print('moy_spécificité: %f' % mean(scores3))
    print("-------------------------------------------------")
    print('MCC :',scores4)
    print('MCC: %f' % mean(scores4))
    print("-------------------------------------------------")
    print('precision-po:',scores5)
    print('moy_precision-po: %f' % mean(scores5))
    print("-------------------------------------------------")
    print('precision-ne :',scores6)
    print('moy_precision-ne: %f' % mean(scores6))
    print("-------------------------------------------------")
    print('AUC :',scores7)
    print('moy_AUC: %f' % mean(scores7))
    print("-------------------------------------------------")
    print('VN :',scores8)
    print('VP :',scores9)
    print('FP :',scores10)
    print('FN :',scores11)
    print("-------------------------------------------------")
    print("-------------------------------------------------")

Gradient_boosting
Accuracy: [0.92156863 0.8627451  0.8627451  0.90196078 0.88      ]
moy_accuracy: 0.885804
-------------------------------------------------
sensibilité : [0.87096774 0.86363636 0.83333333 0.9        0.91666667]
moy_sensibilité: 0.876921
-------------------------------------------------
spécificité : [1.         0.86206897 0.9047619  0.90322581 0.84615385]
moy_spécificité: 0.903242
-------------------------------------------------
MCC : [0.85194275 0.7223168  0.72777172 0.7968255  0.76282051]
MCC: 0.772335
-------------------------------------------------
precision-po: [1.         0.82608696 0.92592593 0.85714286 0.84615385]
moy_precision-po: 0.891062
-------------------------------------------------
precision-ne : [0.83333333 0.89285714 0.79166667 0.93333333 0.91666667]
moy_precision-ne: 0.873571
-------------------------------------------------
AUC : [0.90645161 0.90517241 0.84126984 0.94516129 0.86458333]
moy_AUC: 0.892528
-------------------------------------------------
VN : [20 25 19 28 22]
VP : [27 19 25 18 22]
FP : [0 4 2 3 4]
FN : [4 3 5 2 2]
-------------------------------------------------
-------------------------------------------------

In [ ]:
lst2=['X_long','Min_IRM','VarT_ann_TempJ','VarT_cy_TempJ','VarT_tri_NDVI','IR_sd','RV_Min','Bio_Tint','Bio_Pre_sec','Prec_Avril','Prec_Juin','Prec_Juill','Prec_Aout','Prec_Dec','Tmax_Janv','Tmax_Avril','Tmax_Sept','Tmax_Oct','Tmin_Mai','Tmin_Juin','Vap_Mai','Vent_Juin']

In [ ]:
X2=X[lst2]

In [ ]:
X2.columns

Index(['X_long', 'Min_IRM', 'VarT_ann_TempJ', 'VarT_cy_TempJ', 'VarT_tri_NDVI',
       'IR_sd', 'RV_Min', 'Bio_Tint', 'Bio_Pre_sec', 'Prec_Avril', 'Prec_Juin',
       'Prec_Juill', 'Prec_Aout', 'Prec_Dec', 'Tmax_Janv', 'Tmax_Avril',
       'Tmax_Sept', 'Tmax_Oct', 'Tmin_Mai', 'Tmin_Juin', 'Vap_Mai',
       'Vent_Juin'],
      dtype='object')

In [ ]:
X2

,X_long,Min_IRM,VarT_ann_TempJ,VarT_cy_TempJ,VarT_tri_NDVI,IR_sd,RV_Min,Bio_Tint,Bio_Pre_sec,Prec_Avril,...,Prec_Aout,Prec_Dec,Tmax_Janv,Tmax_Avril,Tmax_Sept,Tmax_Oct,Tmin_Mai,Tmin_Juin,Vap_Mai,Vent_Juin
0,-15.911420,2690,30,53,0,0.899761,0.000009,12.000000,0,1,...,3,15,21.5,22.600000,26.500000,26.000000,16.200001,17.299999,1.72,7.1
1,-13.188370,3350,74,87,0,0.397748,0.000002,17.700001,0,1,...,0,8,21.9,24.600000,29.200001,27.600000,15.700000,17.299999,1.62,6.4
2,-13.188370,3350,74,87,0,0.397748,0.000002,17.700001,0,1,...,0,8,21.9,24.600000,29.200001,27.600000,15.700000,17.299999,1.62,6.4
3,-13.185620,2930,74,85,0,1.639937,0.000054,17.400001,0,1,...,0,8,21.9,24.600000,29.200001,27.600000,16.000000,17.600000,1.64,6.2
4,-13.167180,2350,66,77,0,3.913587,0.000150,17.500000,0,1,...,0,8,22.0,24.700001,29.400000,27.799999,16.100000,17.700001,1.65,5.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,-5.366667,880,92,94,0,2.176535,0.000547,18.300001,1,58,...,3,132,15.2,18.900000,25.700001,22.100000,15.400000,18.500000,1.47,3.9
250,-5.816667,1400,94,95,1,1.735360,0.000052,17.699999,1,65,...,2,142,14.5,18.700001,25.700001,22.400000,16.000000,19.400000,1.48,3.7
251,-5.366667,1080,91,93,1,3.989664,0.000710,18.200001,1,58,...,4,133,15.3,18.900000,25.600000,22.000000,15.300000,18.400000,1.47,4.0
252,-5.558611,620,0,0,2,12.156531,0.000286,18.299999,1,62,...,2,140,16.6,19.799999,25.500000,22.299999,13.600000,16.700001,1.52,4.1
253,-5.483333,990,91,92,1,19.463408,0.002183,17.700000,1,62,...,3,141,16.0,19.000000,24.799999,21.900000,13.600000,16.600000,1.49,3.8

In [ ]:
classifiers = {
"Gradient_boosting": GradientBoostingClassifier(random_state=0)
}

cv = KFold(n_splits=5, random_state=1, shuffle=True)
for name, clf in classifiers.items():
    print(name)
    # evaluate model
    scores1 = cross_val_score(clf,  X2, y, scoring='accuracy', cv=cv, n_jobs=-1)
    scores2 = cross_val_score(clf,  X2, y, scoring='recall', cv=cv, n_jobs=-1)
    scores3 = cross_val_score(clf, X2, y, scoring=my_scorer, cv=cv, n_jobs=-1)
    scores4 = cross_val_score(clf, X2, y, scoring=my_scorer1, cv=cv, n_jobs=-1)
    scores5 = cross_val_score(clf, X2, y, scoring=my_scorer2, cv=cv, n_jobs=-1)
    scores6 = cross_val_score(clf, X2, y, scoring=my_scorer3, cv=cv, n_jobs=-1)
    scores7 = cross_val_score(clf,  X2, y, scoring='roc_auc', cv=cv, n_jobs=-1)
    scores8 = cross_val_score(clf,  X2, y, scoring=my_scorer4, cv=cv, n_jobs=-1)
    scores9 = cross_val_score(clf,  X2, y, scoring=my_scorer5, cv=cv, n_jobs=-1)
    scores10 = cross_val_score(clf,  X2, y, scoring=my_scorer6, cv=cv, n_jobs=-1)
    scores11 = cross_val_score(clf,  X2, y, scoring=my_scorer7, cv=cv, n_jobs=-1)
    # report performance
    print('Accuracy:',scores1)
    print('moy_accuracy: %f' % mean(scores1))
    print("-------------------------------------------------")
    print('sensibilité :',scores2)
    print('moy_sensibilité: %f' % mean(scores2))
    print("-------------------------------------------------")
    print('spécificité :',scores3)
    print('moy_spécificité: %f' % mean(scores3))
    print("-------------------------------------------------")
    print('MCC :',scores4)
    print('MCC: %f' % mean(scores4))
    print("-------------------------------------------------")
    print('precision-po:',scores5)
    print('moy_precision-po: %f' % mean(scores5))
    print("-------------------------------------------------")
    print('precision-ne :',scores6)
    print('moy_precision-ne: %f' % mean(scores6))
    print("-------------------------------------------------")
    print('AUC :',scores7)
    print('moy_AUC: %f' % mean(scores7))
    print("-------------------------------------------------")
    print('VN :',scores8)
    print('VP :',scores9)
    print('FP :',scores10)
    print('FN :',scores11)
    print("-------------------------------------------------")
    print("-------------------------------------------------")

Gradient_boosting
Accuracy: [0.90196078 0.8627451  0.88235294 0.92156863 0.84      ]
moy_accuracy: 0.881725
-------------------------------------------------
sensibilité : [0.83870968 0.86363636 0.83333333 0.95       0.875     ]
moy_sensibilité: 0.872136
-------------------------------------------------
spécificité : [1.         0.86206897 0.95238095 0.90322581 0.80769231]
moy_spécificité: 0.905074
-------------------------------------------------
MCC : [0.81912621 0.7223168  0.77353193 0.84110359 0.68269231]
MCC: 0.767754
-------------------------------------------------
precision-po: [1.         0.82608696 0.96153846 0.86363636 0.80769231]
moy_precision-po: 0.891791
-------------------------------------------------
precision-ne : [0.8        0.89285714 0.8        0.96551724 0.875     ]
moy_precision-ne: 0.866675
-------------------------------------------------
AUC : [0.90967742 0.9130094  0.85555556 0.9483871  0.84294872]
moy_AUC: 0.893916
-------------------------------------------------
VN : [20 25 20 28 21]
VP : [26 19 25 19 21]
FP : [0 4 1 3 5]
FN : [5 3 5 1 3]
-------------------------------------------------
-------------------------------------------------

In [ ]:
set1 = set(lst1)
set2 = set(lst2)

In [ ]:
intersection = list(set1 & set2)
print(intersection)

['IR_sd', 'VarT_tri_NDVI', 'Prec_Avril', 'Prec_Juill', 'Prec_Dec', 'Prec_Aout', 'Bio_Tint', 'Prec_Juin', 'Tmax_Avril', 'Tmax_Sept', 'Vent_Juin', 'Tmax_Janv', 'RV_Min', 'Vap_Mai', 'X_long', 'Tmin_Juin', 'Min_IRM', 'VarT_ann_TempJ']

In [ ]:
len(intersection)

18

In [ ]:
MI=['X_long', 'VegInond', 'Min_IRM', 'VarT_cy_TempJ', 'Geom_maj','IR_sd','Bio_Tint', 'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept', 'Tmin_Avril', 'Tmin_Juin']

In [ ]:
setI=set(MI)

In [ ]:
intersection2 = list(setI & set(intersection))
print(intersection2)

['IR_sd', 'Prec_Juill', 'Bio_Tint', 'Tmax_Avril', 'Tmax_Janv', 'X_long', 'Tmin_Juin', 'Min_IRM', 'Tmax_Sept']

In [ ]:
len(intersection2)

9

In [ ]:
intersection2

['IR_sd',
 'Prec_Juill',
 'Bio_Tint',
 'Tmax_Avril',
 'Tmax_Janv',
 'X_long',
 'Tmin_Juin',
 'Min_IRM',
 'Tmax_Sept']

In [ ]:
XT=X[intersection2]

In [ ]:
classifiers = {
"Gradient_boosting": GradientBoostingClassifier(random_state=0)
}

cv = KFold(n_splits=5, random_state=1, shuffle=True)
for name, clf in classifiers.items():
    print(name)
    # evaluate model
    scores1 = cross_val_score(clf,  XT, y, scoring='accuracy', cv=cv, n_jobs=-1)
    scores2 = cross_val_score(clf,  XT, y, scoring='recall', cv=cv, n_jobs=-1)
    scores3 = cross_val_score(clf, XT, y, scoring=my_scorer, cv=cv, n_jobs=-1)
    scores4 = cross_val_score(clf, XT, y, scoring=my_scorer1, cv=cv, n_jobs=-1)
    scores5 = cross_val_score(clf, XT, y, scoring=my_scorer2, cv=cv, n_jobs=-1)
    scores6 = cross_val_score(clf, XT, y, scoring=my_scorer3, cv=cv, n_jobs=-1)
    scores7 = cross_val_score(clf,  XT, y, scoring='roc_auc', cv=cv, n_jobs=-1)
    scores8 = cross_val_score(clf,  XT, y, scoring=my_scorer4, cv=cv, n_jobs=-1)
    scores9 = cross_val_score(clf,  XT, y, scoring=my_scorer5, cv=cv, n_jobs=-1)
    scores10 = cross_val_score(clf,  XT, y, scoring=my_scorer6, cv=cv, n_jobs=-1)
    scores11 = cross_val_score(clf,  XT, y, scoring=my_scorer7, cv=cv, n_jobs=-1)
    # report performance
    print('Accuracy:',scores1)
    print('moy_accuracy: %f' % mean(scores1))
    print("-------------------------------------------------")
    print('sensibilité :',scores2)
    print('moy_sensibilité: %f' % mean(scores2))
    print("-------------------------------------------------")
    print('spécificité :',scores3)
    print('moy_spécificité: %f' % mean(scores3))
    print("-------------------------------------------------")
    print('MCC :',scores4)
    print('MCC: %f' % mean(scores4))
    print("-------------------------------------------------")
    print('precision-po:',scores5)
    print('moy_precision-po: %f' % mean(scores5))
    print("-------------------------------------------------")
    print('precision-ne :',scores6)
    print('moy_precision-ne: %f' % mean(scores6))
    print("-------------------------------------------------")
    print('AUC :',scores7)
    print('moy_AUC: %f' % mean(scores7))
    print("-------------------------------------------------")
    print('VN :',scores8)
    print('VP :',scores9)
    print('FP :',scores10)
    print('FN :',scores11)
    print("-------------------------------------------------")
    print("-------------------------------------------------")

Gradient_boosting
Accuracy: [0.82352941 0.82352941 0.82352941 0.84313725 0.72      ]
moy_accuracy: 0.806745
-------------------------------------------------
sensibilité : [0.77419355 0.86363636 0.8        0.9        0.75      ]
moy_sensibilité: 0.817566
-------------------------------------------------
spécificité : [0.9        0.79310345 0.85714286 0.80645161 0.69230769]
moy_spécificité: 0.809801
-------------------------------------------------
MCC : [0.65845145 0.65064936 0.6479516  0.69102023 0.44230769]
MCC: 0.618076
-------------------------------------------------
precision-po: [0.92307692 0.76       0.88888889 0.75       0.69230769]
moy_precision-po: 0.802855
-------------------------------------------------
precision-ne : [0.72       0.88461538 0.75       0.92592593 0.75      ]
moy_precision-ne: 0.806108
-------------------------------------------------
AUC : [0.85967742 0.87382445 0.82063492 0.91612903 0.79246795]
moy_AUC: 0.852547
-------------------------------------------------
VN : [18 23 18 25 18]
VP : [24 19 24 18 18]
FP : [2 6 3 6 8]
FN : [7 3 6 2 6]
-------------------------------------------------
-------------------------------------------------

In [ ]:
intersection

['IR_sd',
 'VarT_tri_NDVI',
 'Prec_Avril',
 'Prec_Juill',
 'Prec_Dec',
 'Prec_Aout',
 'Bio_Tint',
 'Prec_Juin',
 'Tmax_Avril',
 'Tmax_Sept',
 'Vent_Juin',
 'Tmax_Janv',
 'RV_Min',
 'Vap_Mai',
 'X_long',
 'Tmin_Juin',
 'Min_IRM',
 'VarT_ann_TempJ']

In [ ]:
XT=X[intersection]

In [ ]:
classifiers = {
"Gradient_boosting": GradientBoostingClassifier(random_state=0)
}

cv = KFold(n_splits=5, random_state=1, shuffle=True)
for name, clf in classifiers.items():
    print(name)
    # evaluate model
    scores1 = cross_val_score(clf,  XT, y, scoring='accuracy', cv=cv, n_jobs=-1)
    scores2 = cross_val_score(clf,  XT, y, scoring='recall', cv=cv, n_jobs=-1)
    scores3 = cross_val_score(clf, XT, y, scoring=my_scorer, cv=cv, n_jobs=-1)
    scores4 = cross_val_score(clf, XT, y, scoring=my_scorer1, cv=cv, n_jobs=-1)
    scores5 = cross_val_score(clf, XT, y, scoring=my_scorer2, cv=cv, n_jobs=-1)
    scores6 = cross_val_score(clf, XT, y, scoring=my_scorer3, cv=cv, n_jobs=-1)
    scores7 = cross_val_score(clf,  XT, y, scoring='roc_auc', cv=cv, n_jobs=-1)
    scores8 = cross_val_score(clf,  XT, y, scoring=my_scorer4, cv=cv, n_jobs=-1)
    scores9 = cross_val_score(clf,  XT, y, scoring=my_scorer5, cv=cv, n_jobs=-1)
    scores10 = cross_val_score(clf,  XT, y, scoring=my_scorer6, cv=cv, n_jobs=-1)
    scores11 = cross_val_score(clf,  XT, y, scoring=my_scorer7, cv=cv, n_jobs=-1)
    # report performance
    print('Accuracy:',scores1)
    print('moy_accuracy: %f' % mean(scores1))
    print("-------------------------------------------------")
    print('sensibilité :',scores2)
    print('moy_sensibilité: %f' % mean(scores2))
    print("-------------------------------------------------")
    print('spécificité :',scores3)
    print('moy_spécificité: %f' % mean(scores3))
    print("-------------------------------------------------")
    print('MCC :',scores4)
    print('MCC: %f' % mean(scores4))
    print("-------------------------------------------------")
    print('precision-po:',scores5)
    print('moy_precision-po: %f' % mean(scores5))
    print("-------------------------------------------------")
    print('precision-ne :',scores6)
    print('moy_precision-ne: %f' % mean(scores6))
    print("-------------------------------------------------")
    print('AUC :',scores7)
    print('moy_AUC: %f' % mean(scores7))
    print("-------------------------------------------------")
    print('VN :',scores8)
    print('VP :',scores9)
    print('FP :',scores10)
    print('FN :',scores11)
    print("-------------------------------------------------")
    print("-------------------------------------------------")

Gradient_boosting
Accuracy: [0.90196078 0.88235294 0.78431373 0.92156863 0.82      ]
moy_accuracy: 0.862039
-------------------------------------------------
sensibilité : [0.83870968 0.90909091 0.73333333 0.95       0.875     ]
moy_sensibilité: 0.861227
-------------------------------------------------
spécificité : [1.         0.86206897 0.85714286 0.90322581 0.76923077]
moy_spécificité: 0.878334
-------------------------------------------------
MCC : [0.81912621 0.76518643 0.58132097 0.84110359 0.64578501]
MCC: 0.730504
-------------------------------------------------
precision-po: [1.         0.83333333 0.88       0.86363636 0.77777778]
moy_precision-po: 0.870949
-------------------------------------------------
precision-ne : [0.8        0.92592593 0.69230769 0.96551724 0.86956522]
moy_precision-ne: 0.850663
-------------------------------------------------
AUC : [0.90483871 0.90987461 0.84126984 0.94032258 0.86458333]
moy_AUC: 0.892178
-------------------------------------------------
VN : [20 25 18 28 20]
VP : [26 20 22 19 21]
FP : [0 4 3 3 6]
FN : [5 2 8 1 3]
-------------------------------------------------
-------------------------------------------------

In [ ]:
clmns=X.columns

In [ ]:
clmns

Index(['X_long', 'Y_lat', 'Bovins', 'Volaille', 'Caprins', 'Ovins', 'Equides',
       'Coniferes', 'ZoneAride', 'ZonePel',
       ...
       'Vent_Mars', 'Vent_Avril', 'Vent_Mai', 'Vent_Juin', 'Vent_Juill',
       'Vent_Aout', 'Vent_Sept', 'Vent_Oct', 'Vent_Nov', 'Vent_Dec'],
      dtype='object', length=225)

In [ ]:
def transform(X, fs) :
  X_ = X.copy()
  for i in range(len(fs)) :
    if fs[i] == False :
      X_.drop([clmns[i]], axis=1, inplace=True)
  return X_

In [ ]:
def Retransform (lst):
  Fs=[]      
  for i in range(225):
    if clmns[i] in lst :
       Fs.append(True)
    else :
       Fs.append(False)
  return Fs

In [ ]:
lst=intersection2

In [ ]:
Fs_mcc = Retransform (lst)

In [ ]:
Fs_mcc

[True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

In [ ]:
transform(X,Fs_mcc)

,X_long,Min_IRM,IR_sd,Bio_Tint,Prec_Juill,Tmax_Janv,Tmax_Avril,Tmax_Sept,Tmin_Juin
0,-15.911420,2690,0.899761,12.000000,1,21.5,22.600000,26.500000,17.299999
1,-13.188370,3350,0.397748,17.700001,0,21.9,24.600000,29.200001,17.299999
2,-13.188370,3350,0.397748,17.700001,0,21.9,24.600000,29.200001,17.299999
3,-13.185620,2930,1.639937,17.400001,0,21.9,24.600000,29.200001,17.600000
4,-13.167180,2350,3.913587,17.500000,0,22.0,24.700001,29.400000,17.700001
...,...,...,...,...,...,...,...,...,...
249,-5.366667,880,2.176535,18.300001,1,15.2,18.900000,25.700001,18.500000
250,-5.816667,1400,1.735360,17.699999,1,14.5,18.700001,25.700001,19.400000
251,-5.366667,1080,3.989664,18.200001,1,15.3,18.900000,25.600000,18.400000
252,-5.558611,620,12.156531,18.299999,1,16.6,19.799999,25.500000,16.700001
253,-5.483333,990,19.463408,17.700000,1,16.0,19.000000,24.799999,16.600000

In [ ]:
cv = KFold(n_splits=5, random_state=1, shuffle=True)
explored_models_mcc = []
scores_mcc = []
models_mm_mcc=[]
var_mcc=[]
def explor_mcc(fs, mcc, algo) :
  if (sum(fs) > 225) :
    return
  explored_models_mcc.append(fs)
  for i in range(225) :
    neighbor = fs.copy()
    neighbor[i] = not fs[i]
    if (neighbor not in explored_models_mcc) :
      score_mcc = cross_val_score(algo, transform(X, neighbor) , y, scoring=my_scorer1, cv=cv, n_jobs=-1)
      mean_score_mcc = np.mean(score_mcc)
      explored_models_mcc.append(neighbor)
      if (mean_score_mcc  > mcc) :
        models_mm_mcc.append(neighbor)
        print("mcc : %f" % mean_score_mcc)
        print(len(transform(X,neighbor).columns))
        print(transform(X,neighbor).columns)
        print("-----------")
        scores_mcc.append(mean_score_mcc)
        var_mcc.append(transform(X,neighbor))
        explor_mcc(neighbor, mean_score_mcc, algo)

In [ ]:
algo=GradientBoostingClassifier(random_state=0)

In [ ]:
explor_mcc(Fs_mcc,0.618076,algo)

mcc : 0.623293
10
Index(['X_long', 'Bovins', 'Min_IRM', 'IR_sd', 'Bio_Tint', 'Prec_Juill',
       'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.639287
11
Index(['X_long', 'Bovins', 'Autres', 'Min_IRM', 'IR_sd', 'Bio_Tint',
       'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.646095
10
Index(['X_long', 'Autres', 'Min_IRM', 'IR_sd', 'Bio_Tint', 'Prec_Juill',
       'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.649149
11
Index(['X_long', 'Lesfeuillus', 'Autres', 'Min_IRM', 'IR_sd', 'Bio_Tint',
       'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.651935
12
Index(['X_long', 'Bovins', 'Lesfeuillus', 'Autres', 'Min_IRM', 'IR_sd',
       'Bio_Tint', 'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept',
       'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.655028
13
Index(['X_long', 'Bovins', 'Lesfeuillus', 'Autres', 'Min_IRM', 'Substratum',
       'IR_sd', 'Bio_Tint', 'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril',
       'Tmax_Sept', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.658787
14
Index(['X_long', 'Bovins', 'ZonePel', 'Lesfeuillus', 'Autres', 'Min_IRM',
       'Substratum', 'IR_sd', 'Bio_Tint', 'Prec_Juill', 'Tmax_Janv',
       'Tmax_Avril', 'Tmax_Sept', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.663782
15
Index(['X_long', 'Bovins', 'ZonePel', 'Lesfeuillus', 'Autres', 'Min_IRM',
       'Substratum', 'IR_sd', 'Bio_Tint', 'Bio_Pre_Qsec', 'Prec_Juill',
       'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.665471
16
Index(['X_long', 'Bovins', 'ZonePel', 'Lesfeuillus', 'Autres', 'Min_IRM',
       'Substratum', 'IR_sd', 'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec',
       'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.673696
17
Index(['X_long', 'Bovins', 'ZonePel', 'Lesfeuillus', 'Caduc', 'Autres',
       'Min_IRM', 'Substratum', 'IR_sd', 'Bio_Tint', 'Bio_Pre_Ann',
       'Bio_Pre_Qsec', 'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept',
       'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.678836
16
Index(['X_long', 'ZonePel', 'Lesfeuillus', 'Caduc', 'Autres', 'Min_IRM',
       'Substratum', 'IR_sd', 'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec',
       'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.681172
15
Index(['X_long', 'Lesfeuillus', 'Caduc', 'Autres', 'Min_IRM', 'Substratum',
       'IR_sd', 'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec', 'Prec_Juill',
       'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.689740
16
Index(['X_long', 'Coniferes', 'Lesfeuillus', 'Caduc', 'Autres', 'Min_IRM',
       'Substratum', 'IR_sd', 'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec',
       'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.681899
14
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'Substratum', 'IR_sd',
       'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec', 'Prec_Juill', 'Tmax_Janv',
       'Tmax_Avril', 'Tmax_Sept', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.687024
15
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'Min_EVI', 'Substratum',
       'IR_sd', 'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec', 'Prec_Juill',
       'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.689079
15
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'Substratum', 'Sol_Limon',
       'IR_sd', 'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec', 'Prec_Juill',
       'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.691894
16
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'VarT_tri_TempJ', 'Substratum',
       'Sol_Limon', 'IR_sd', 'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec',
       'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.691932
17
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'VarT_tri_TempJ', 'Substratum',
       'Sol_Limon', 'IR_sd', 'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec',
       'Prec_Juill', 'Rad_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept',
       'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.691149
16
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'Substratum', 'Sol_Limon',
       'IR_sd', 'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec', 'Prec_Juin',
       'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.697007
17
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'Substratum', 'Sol_Limon',
       'Pente_sd', 'IR_sd', 'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec',
       'Prec_Juin', 'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept',
       'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.703570
18
Index(['X_long', 'Caduc', 'Autres', 'VegInond', 'Min_IRM', 'Substratum',
       'Sol_Limon', 'Pente_sd', 'IR_sd', 'Bio_Tint', 'Bio_Pre_Ann',
       'Bio_Pre_Qsec', 'Prec_Juin', 'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril',
       'Tmax_Sept', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.688074
15
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'Substratum', 'IR_sd', 'RV_Max',
       'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec', 'Prec_Juill', 'Tmax_Janv',
       'Tmax_Avril', 'Tmax_Sept', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.704279
16
Index(['X_long', 'Caduc', 'Autres', 'Moy_IRM', 'Min_IRM', 'Substratum',
       'IR_sd', 'RV_Max', 'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec',
       'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.710817
17
Index(['X_long', 'Caduc', 'Autres', 'Moy_IRM', 'Min_IRM', 'Substratum',
       'IR_sd', 'RV_Max', 'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec',
       'Prec_Juill', 'Tmax_Janv', 'Tmax_Mars', 'Tmax_Avril', 'Tmax_Sept',
       'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.722989
17
Index(['X_long', 'Caduc', 'Autres', 'Moy_IRM', 'Min_IRM', 'Substratum',
       'IR_sd', 'RV_Max', 'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec',
       'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept', 'Tmin_Juin',
       'Tmin_Aout'],
      dtype='object')
-----------
mcc : 0.725275
18
Index(['X_long', 'ZonePel', 'Caduc', 'Autres', 'Moy_IRM', 'Min_IRM',
       'Substratum', 'IR_sd', 'RV_Max', 'Bio_Tint', 'Bio_Pre_Ann',
       'Bio_Pre_Qsec', 'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept',
       'Tmin_Juin', 'Tmin_Aout'],
      dtype='object')
-----------
mcc : 0.724357
18
Index(['X_long', 'Caduc', 'Autres', 'Moy_IRM', 'Min_IRM', 'Substratum',
       'IR_sd', 'RV_Max', 'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec',
       'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept', 'Tmin_Juin',
       'Tmin_Aout', 'Vent_Fev'],
      dtype='object')
-----------
mcc : 0.726755
19
Index(['X_long', 'Caduc', 'Autres', 'Moy_IRM', 'Min_IRM', 'Substratum',
       'IR_sd', 'RV_Max', 'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec',
       'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept', 'Tmin_Juin',
       'Tmin_Aout', 'Vent_Janv', 'Vent_Fev'],
      dtype='object')
-----------
mcc : 0.696706
16
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'Moy_NDVI', 'Substratum',
       'IR_sd', 'RV_Max', 'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec',
       'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.699360
17
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'Moy_NDVI', 'Substratum',
       'IR_sd', 'RV_Max', 'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec',
       'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept', 'Tmin_Mars',
       'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.701348
18
Index(['X_long', 'Caduc', 'Autres', 'Pl_herb', 'Min_IRM', 'Moy_NDVI',
       'Substratum', 'IR_sd', 'RV_Max', 'Bio_Tint', 'Bio_Pre_Ann',
       'Bio_Pre_Qsec', 'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept',
       'Tmin_Mars', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.721557
18
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'Moy_NDVI', 'Substratum',
       'IR_sd', 'RV_Max', 'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_sec',
       'Bio_Pre_Qsec', 'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept',
       'Tmin_Mars', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.700965
18
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'Moy_NDVI', 'Substratum',
       'IR_sd', 'RV_Max', 'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec',
       'Prec_Juin', 'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept',
       'Tmin_Mars', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.701062
19
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'Moy_NDVI', 'Substratum',
       'Sol_Carbone', 'IR_sd', 'RV_Max', 'Bio_Tint', 'Bio_Pre_Ann',
       'Bio_Pre_Qsec', 'Prec_Juin', 'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril',
       'Tmax_Sept', 'Tmin_Mars', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.712812
19
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'Moy_NDVI', 'Substratum',
       'Pente_sd', 'IR_sd', 'RV_Max', 'Bio_Tint', 'Bio_Pre_Ann',
       'Bio_Pre_Qsec', 'Prec_Juin', 'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril',
       'Tmax_Sept', 'Tmin_Mars', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.714620
20
Index(['X_long', 'Caduc', 'Autres', 'VegInond', 'Min_IRM', 'Moy_NDVI',
       'Substratum', 'Pente_sd', 'IR_sd', 'RV_Max', 'Bio_Tint', 'Bio_Pre_Ann',
       'Bio_Pre_Qsec', 'Prec_Juin', 'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril',
       'Tmax_Sept', 'Tmin_Mars', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.716966
20
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'VarT_tri_TempJ', 'Moy_NDVI',
       'Substratum', 'Pente_sd', 'IR_sd', 'RV_Max', 'Bio_Tint', 'Bio_Pre_Ann',
       'Bio_Pre_Qsec', 'Prec_Juin', 'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril',
       'Tmax_Sept', 'Tmin_Mars', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.720232
20
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'VarT_tri_TempN', 'Moy_NDVI',
       'Substratum', 'Pente_sd', 'IR_sd', 'RV_Max', 'Bio_Tint', 'Bio_Pre_Ann',
       'Bio_Pre_Qsec', 'Prec_Juin', 'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril',
       'Tmax_Sept', 'Tmin_Mars', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.709173
19
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'Moy_NDVI', 'Substratum',
       'IR_sd', 'RV_Max', 'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec',
       'Prec_Juin', 'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept',
       'Tmax_Oct', 'Tmin_Mars', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.692989
16
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'Substratum', 'IR_sd', 'RV_Max',
       'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec', 'Prec_Juill', 'Tmax_Janv',
       'Tmax_Avril', 'Tmax_Sept', 'Tmin_Mai', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.704083
17
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'VarT_tri_TempJ', 'Substratum',
       'IR_sd', 'RV_Max', 'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec',
       'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept', 'Tmin_Mai',
       'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.697043
17
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'VarT_tri_TempN', 'Substratum',
       'IR_sd', 'RV_Max', 'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec',
       'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept', 'Tmin_Mai',
       'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.699838
16
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'VarT_tri_TempN', 'Substratum',
       'IR_sd', 'RV_Max', 'Bio_Tint', 'Bio_Pre_Ann', 'Prec_Juill', 'Tmax_Janv',
       'Tmax_Avril', 'Tmax_Sept', 'Tmin_Mai', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.704683
17
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'VarT_tri_TempN', 'Substratum',
       'IR_sd', 'RV_Max', 'RV_Med', 'Bio_Tint', 'Bio_Pre_Ann', 'Prec_Juill',
       'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept', 'Tmin_Mai', 'Tmin_Juin'],
      dtype='object')
-----------
mcc : 0.700806
18
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'VarT_tri_TempN', 'Substratum',
       'IR_sd', 'RV_Max', 'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec',
       'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept', 'Tmin_Mai',
       'Tmin_Juin', 'Vap_Aout'],
      dtype='object')
-----------
mcc : 0.697544
14
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'Substratum', 'IR_sd', 'RV_Max',
       'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec', 'Prec_Juill', 'Tmax_Janv',
       'Tmax_Avril', 'Tmax_Sept'],
      dtype='object')
-----------
mcc : 0.704629
15
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'Substratum', 'Pente_Max',
       'IR_sd', 'RV_Max', 'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec',
       'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept'],
      dtype='object')
-----------
mcc : 0.710784
16
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'Substratum', 'Pente_Max',
       'IR_sd', 'RV_Max', 'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec',
       'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept', 'Vap_Avril'],
      dtype='object')
-----------
mcc : 0.713428
17
Index(['X_long', 'Lesfeuillus', 'Caduc', 'Autres', 'Min_IRM', 'Substratum',
       'Pente_Max', 'IR_sd', 'RV_Max', 'Bio_Tint', 'Bio_Pre_Ann',
       'Bio_Pre_Qsec', 'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept',
       'Vap_Avril'],
      dtype='object')
-----------
mcc : 0.715359
18
Index(['X_long', 'Lesfeuillus', 'Caduc', 'Autres', 'Min_IRM', 'Substratum',
       'Pente_Max', 'IR_sd', 'RV_Max', 'Bio_Tint', 'Bio_Pre_Ann',
       'Bio_Pre_Qsec', 'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept',
       'Vap_Janv', 'Vap_Avril'],
      dtype='object')
-----------
mcc : 0.721827
19
Index(['X_long', 'ZonePel', 'Lesfeuillus', 'Caduc', 'Autres', 'Min_IRM',
       'Substratum', 'Pente_Max', 'IR_sd', 'RV_Max', 'Bio_Tint', 'Bio_Pre_Ann',
       'Bio_Pre_Qsec', 'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept',
       'Vap_Janv', 'Vap_Avril'],
      dtype='object')
-----------
mcc : 0.711942
17
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'Substratum', 'Pente_Max',
       'IR_sd', 'RV_Max', 'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec',
       'Prec_Juill', 'Rad_Avril', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept',
       'Vap_Avril'],
      dtype='object')
-----------
mcc : 0.697814
15
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'Substratum', 'IR_sd', 'RV_Max',
       'RV_Min', 'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec', 'Prec_Juill',
       'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept'],
      dtype='object')
-----------
mcc : 0.698426
16
Index(['X_long', 'Caduc', 'Autres', 'Min_IRM', 'VarT_bi_TempN', 'Substratum',
       'IR_sd', 'RV_Max', 'RV_Min', 'Bio_Tint', 'Bio_Pre_Ann', 'Bio_Pre_Qsec',
       'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept'],
      dtype='object')
-----------
mcc : 0.705235
17
Index(['X_long', 'Lesfeuillus', 'Caduc', 'Autres', 'Min_IRM', 'VarT_bi_TempN',
       'Substratum', 'IR_sd', 'RV_Max', 'RV_Min', 'Bio_Tint', 'Bio_Pre_Ann',
       'Bio_Pre_Qsec', 'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept'],
      dtype='object')
-----------
mcc : 0.707848
18
Index(['X_long', 'Lesfeuillus', 'Caduc', 'Autres', 'VegInond', 'Min_IRM',
       'VarT_bi_TempN', 'Substratum', 'IR_sd', 'RV_Max', 'RV_Min', 'Bio_Tint',
       'Bio_Pre_Ann', 'Bio_Pre_Qsec', 'Prec_Juill', 'Tmax_Janv', 'Tmax_Avril',
       'Tmax_Sept'],
      dtype='object')
-----------

In [ ]:
explor_mcc(Fs_mcc,0.730504,algo)

mcc : 0.734518
19
Index(['X_long', 'Min_IRM', 'VarT_ann_TempJ', 'VarT_tri_NDVI', 'Ret_eau',
       'IR_sd', 'RV_Min', 'Bio_Tint', 'Prec_Avril', 'Prec_Juin', 'Prec_Juill',
       'Prec_Aout', 'Prec_Dec', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept',
       'Tmin_Juin', 'Vap_Mai', 'Vent_Juin'],
      dtype='object')
-----------
mcc : 0.731327
19
Index(['X_long', 'Min_IRM', 'VarT_ann_TempJ', 'VarT_tri_NDVI', 'Geom_maj',
       'IR_sd', 'RV_Min', 'Bio_Tint', 'Prec_Avril', 'Prec_Juin', 'Prec_Juill',
       'Prec_Aout', 'Prec_Dec', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept',
       'Tmin_Juin', 'Vap_Mai', 'Vent_Juin'],
      dtype='object')
-----------
mcc : 0.731499
20
Index(['X_long', 'Min_IRM', 'VarT_ann_TempJ', 'Amp3_NDVI', 'VarT_tri_NDVI',
       'Geom_maj', 'IR_sd', 'RV_Min', 'Bio_Tint', 'Prec_Avril', 'Prec_Juin',
       'Prec_Juill', 'Prec_Aout', 'Prec_Dec', 'Tmax_Janv', 'Tmax_Avril',
       'Tmax_Sept', 'Tmin_Juin', 'Vap_Mai', 'Vent_Juin'],
      dtype='object')
-----------
mcc : 0.747021
19
Index(['X_long', 'Min_IRM', 'VarT_ann_TempJ', 'VarT_tri_NDVI', 'IR_sd',
       'RV_Min', 'Bio_Tint', 'Prec_Avril', 'Prec_Juin', 'Prec_Juill',
       'Prec_Aout', 'Prec_Oct', 'Prec_Dec', 'Tmax_Janv', 'Tmax_Avril',
       'Tmax_Sept', 'Tmin_Juin', 'Vap_Mai', 'Vent_Juin'],
      dtype='object')
-----------
mcc : 0.731186
19
Index(['X_long', 'Min_IRM', 'VarT_ann_TempJ', 'VarT_tri_NDVI', 'IR_sd',
       'RV_Min', 'Bio_Tint', 'Prec_Avril', 'Prec_Juin', 'Prec_Juill',
       'Prec_Aout', 'Prec_Nov', 'Prec_Dec', 'Tmax_Janv', 'Tmax_Avril',
       'Tmax_Sept', 'Tmin_Juin', 'Vap_Mai', 'Vent_Juin'],
      dtype='object')
-----------
mcc : 0.740570
20
Index(['X_long', 'Min_IRM', 'VarT_ann_TempJ', 'VarT_tri_NDVI', 'IR_sd',
       'RV_Min', 'Bio_Tint', 'Prec_Avril', 'Prec_Juin', 'Prec_Juill',
       'Prec_Aout', 'Prec_Nov', 'Prec_Dec', 'Tmax_Janv', 'Tmax_Avril',
       'Tmax_Sept', 'Tmax_Oct', 'Tmin_Juin', 'Vap_Mai', 'Vent_Juin'],
      dtype='object')
-----------
mcc : 0.753007
19
Index(['X_long', 'Min_IRM', 'VarT_ann_TempJ', 'VarT_tri_NDVI', 'IR_sd',
       'RV_Min', 'Bio_Tint', 'Prec_Avril', 'Prec_Juin', 'Prec_Juill',
       'Prec_Aout', 'Prec_Dec', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept',
       'Tmax_Oct', 'Tmin_Juin', 'Vap_Mai', 'Vent_Juin'],
      dtype='object')
-----------
mcc : 0.734633
18
Index(['X_long', 'Min_IRM', 'VarT_ann_TempJ', 'VarT_tri_NDVI', 'IR_sd',
       'RV_Min', 'Bio_Tint', 'Prec_Avril', 'Prec_Juin', 'Prec_Juill',
       'Prec_Aout', 'Prec_Nov', 'Prec_Dec', 'Tmax_Janv', 'Tmax_Avril',
       'Tmax_Sept', 'Vap_Mai', 'Vent_Juin'],
      dtype='object')
-----------
mcc : 0.755208
17
Index(['X_long', 'Min_IRM', 'VarT_ann_TempJ', 'VarT_tri_NDVI', 'IR_sd',
       'RV_Min', 'Bio_Tint', 'Prec_Avril', 'Prec_Juin', 'Prec_Juill',
       'Prec_Aout', 'Prec_Dec', 'Tmax_Janv', 'Tmax_Avril', 'Tmax_Sept',
       'Vap_Mai', 'Vent_Juin'],
      dtype='object')
-----------